a=(4,1,5,8,44,2,67,39,54,12)
b=list(a)
print("\n")
print("----------------------TUPLE TO LIST----------------------")
print(a)
print(b)
c=[3,7,2,65,28,56,2]
d=tuple(c)
print("\n")
print("----------------------LIST TO TUPLE----------------------")
print(c)
print(d)